# Generated by Django 5.0.4 on 2024-04-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListenSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceName', models.CharField(max_length=200)),
                ('resourceUrl', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': '外刊听力资源',
                'verbose_name_plural': '外刊听力资源',
            },
        ),
        migrations.CreateModel(
            name='PastPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitable', models.CharField(max_length=50)),
                ('resourceName', models.CharField(max_length=200)),
                ('resourceUrl', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': '真题听力',
                'verbose_name_plural': '真题听力',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('userlabel', models.CharField(max_length=1000)),
                ('userage', models.CharField(max_length=100)),
                ('user_urge', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='UserListenResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('resourceName', models.CharField(max_length=32)),
                ('has_use_count', models.IntegerField()),
                ('resourceUrl', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': '用户保存音频',
                'verbose_name_plural': '用户保存音频',
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('resourceType', models.CharField(max_length=100)),
                ('resourceUrl', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '用户听力记录',
                'verbose_name_plural': '用户听力记录',
            },
        ),
        migrations.CreateModel(
            name='UserShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=22)),
                ('username', models.CharField(max_length=1000)),
                ('userlabel', models.CharField(max_length=1000)),
                ('userage', models.CharField(max_length=100)),
                ('user_urge', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=1000)),
                ('resourceName', models.CharField(max_length=200)),
                ('resourceUrl', models.CharField(max_length=400)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': '社区动态',
                'verbose_name_plural': '社区动态',
            },
        ),
        migrations.CreateModel(
            name='UserVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
            ],
        ),
    ]
