# Generated by Django 5.0.4 on 2024-04-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueApi', '0002_remove_usershare_id_alter_usershare_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershare',
            name='shareId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usershare',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
