# Generated by Django 5.0.4 on 2024-04-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueApi', '0004_usershare_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
