# Generated by Django 5.0.4 on 2024-04-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueApi', '0005_alter_userinfo_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=1000)),
                ('filename', models.CharField(max_length=2000)),
                ('filesource', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': '云盘资源',
                'verbose_name_plural': '云盘资源',
            },
        ),
    ]
