# Generated by Django 5.0.4 on 2024-04-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueApi', '0006_cloudfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudfiles',
            name='id',
        ),
        migrations.AddField(
            model_name='cloudfiles',
            name='fileId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
