# Generated by Django 5.0.4 on 2024-04-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueApi', '0007_remove_cloudfiles_id_cloudfiles_fileid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfiles',
            name='dir',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
