# Generated by Django 5.0.4 on 2024-04-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueApi', '0008_cloudfiles_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfiles',
            name='dir',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
