# Generated by Django 5.0.4 on 2024-04-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueApi', '0009_alter_cloudfiles_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfiles',
            name='is_dir',
            field=models.CharField(default='false', max_length=20),
            preserve_default=False,
        ),
    ]
