# Generated by Django 5.0.4 on 2024-04-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueApi', '0010_cloudfiles_is_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('friendId', models.CharField(max_length=100)),
            ],
        ),
    ]
