# Generated by Django 5.0.4 on 2024-04-22 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vueApi', '0011_friend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': '好友', 'verbose_name_plural': '好友'},
        ),
    ]
